(require 'autothemer)

(autothemer-deftheme
 onyx "A pastel onyx theme based on Kitty colors"

 ((((class color) (min-colors #xFFFFFF)))
  (onyx-bg      "#0c0c0c")
  (onyx-fg      "#bdc4a7")
  (onyx-black   "#0c0c0c")
  (onyx-grey    "#393D3F")
  (onyx-red     "#DA4167")
  (onyx-red-alt "#F45B69")
  (onyx-green   "#9FC490")
  (onyx-green-alt "#70AE6E")
  (onyx-yellow  "#F9DF74")
  (onyx-yellow-alt "#E6C79C")
  (onyx-blue    "#7180ac")
  (onyx-blue-alt "#5b618a")
  (onyx-magenta "#9D8189")
  (onyx-magenta-alt "#9B5094")
  (onyx-cyan    "#99EDCC")
  (onyx-cyan-alt "#75BBA7")
  (onyx-white   "#D5C5C8")
  (onyx-white-alt "#F7F0F5")
  (onyx-sel-bg  "#293334")
  (onyx-sel-fg  "#cecece")
  (onyx-cursor  "#da627d")
  (onyx-url     "#FFCAD4"))

 ((default (:foreground onyx-fg :background onyx-bg))
  (cursor  (:background onyx-yellow))
  (region  (:background onyx-sel-bg :foreground onyx-sel-fg))
  (highlight (:background onyx-sel-bg :foreground onyx-white))
  (link    (:foreground onyx-url :underline t))
  
  (mode-line           (:background onyx-grey :foreground onyx-fg))
  (mode-line-inactive  (:background onyx-bg :foreground onyx-grey))
  
  (minibuffer-prompt (:foreground onyx-blue :weight 'bold))
  (completions-common-part (:foreground onyx-yellow :weight 'bold)) 
  (completions-first-match (:foreground onyx-yellow :weight 'bold))
  (match (:foreground onyx-yellow :weight 'bold))
  (orderless-match-face-0 (:foreground onyx-yellow :weight 'bold))
  (orderless-match-face-1 (:foreground onyx-yellow :weight 'bold))
  (orderless-match-face-2 (:foreground onyx-yellow :weight 'bold))
  (vertico-current (:background onyx-sel-bg :foreground onyx-white :extend t))
  (completions-highlight (:background onyx-sel-bg :foreground onyx-white :extend t))

  (dired-directory (:foreground onyx-blue :weight 'bold))
  (dired-ignored   (:foreground onyx-grey))
  (dired-flagged   (:foreground onyx-red :background onyx-sel-bg))
  (dired-header    (:foreground onyx-magenta :weight 'bold))
  (dired-symlink   (:foreground onyx-cyan))
  (hl-line         (:background onyx-sel-bg :extend t))
  (ivy-minibuffer-match-face-1 (:foreground onyx-yellow :weight 'bold))
  (ivy-minibuffer-match-face-2 (:foreground onyx-yellow :weight 'bold))
  (ivy-minibuffer-match-face-3 (:foreground onyx-yellow :weight 'bold))
  (ivy-minibuffer-match-face-4 (:foreground onyx-yellow :weight 'bold))

  (magit-section-heading        (:foreground onyx-yellow :weight 'bold))
  (magit-diff-added             (:foreground onyx-green :background "#0f1a0f"))
  (magit-diff-added-highlight   (:foreground onyx-green :background "#1a2a1a"))
  (magit-diff-removed           (:foreground onyx-red   :background "#1a0f0f"))
  (magit-diff-removed-highlight (:foreground onyx-red   :background "#2a1a1a"))
  (magit-hash                   (:foreground onyx-blue))

  (font-lock-builtin-face           (:foreground onyx-blue))
  (font-lock-comment-face           (:foreground onyx-yellow))
  (font-lock-constant-face          (:foreground onyx-cyan))
  (font-lock-function-name-face     (:foreground onyx-yellow))
  (font-lock-keyword-face           (:foreground onyx-magenta :weight 'bold))
  (font-lock-string-face            (:foreground onyx-green))
  (font-lock-type-face              (:foreground onyx-blue-alt))
  (font-lock-variable-name-face      (:foreground onyx-fg))
  (font-lock-warning-face           (:foreground onyx-red :weight 'bold))

  (org-level-1 (:foreground onyx-magenta :weight 'bold :height 1.2))
  (org-level-2 (:foreground onyx-blue :weight 'bold :height 1.1))
  (org-level-3 (:foreground onyx-green :weight 'bold))
  (org-level-4 (:foreground onyx-yellow-alt))
  (org-document-title (:foreground onyx-white-alt :weight 'bold :height 1.5))
  (org-link (:foreground onyx-url :underline t))
  (org-todo (:foreground onyx-red :weight 'bold))
  (org-done (:foreground onyx-green-alt :weight 'bold))
  (org-block (:background "#050505" :extend t))

  (show-paren-match (:foreground onyx-yellow :weight 'bold :underline t))
  (show-paren-mismatch (:background onyx-red :foreground onyx-black :weight 'bold))

  (doom-modeline-bar (:background onyx-magenta))
  (doom-modeline-panel (:background onyx-sel-bg :foreground onyx-fg))
  (doom-modeline-buffer-file (:foreground onyx-fg))
  (doom-modeline-buffer-path (:foreground onyx-blue))
  (doom-modeline-buffer-modified (:foreground onyx-yellow-alt))
  (doom-modeline-project-dir (:foreground onyx-magenta-alt :weight 'bold))
  (doom-modeline-info (:foreground onyx-green)) ; Clean/Info
  (doom-modeline-warning (:foreground onyx-yellow)) ; Modified/Warning
  (doom-modeline-urgent (:foreground onyx-red)) ; Conflicts/Errors
  (doom-modeline-project-dir (:foreground onyx-magenta :weight 'bold))
  (doom-modeline-project-parent (:foreground onyx-blue))
  (doom-modeline-project-root (:foreground onyx-magenta))
  
  (doom-modeline-macro (:foreground onyx-magenta-alt)))

 (custom-theme-set-variables 'onyx
  `(ansi-color-names-vector [,onyx-black ,onyx-red ,onyx-green ,onyx-yellow ,onyx-blue ,onyx-magenta ,onyx-cyan ,onyx-white])
  `(pdf-view-midnight-colors '(,onyx-fg . ,onyx-bg))))

(provide-theme 'onyx)
