;;; Automatically generated by ‘recentf’ on Mon Oct 20 10:01:17 2025.

(setq recentf-list
      '(
        "~/.config/emacs/config.org"
        "~/.config/emacs/early-init.el"
        "~/.config/emacs/themes/latte-theme.el"
        "~/.config/emacs/themes/roseprime-theme.el"
        "~/.config/emacs/bookmarks"
        "~/lang/dsa/structy/hashing/intersection.cpp"
        "~/lang/dsa/pair.cpp"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
